    "use client";
    import { useState } from "react"; import { createClient } from "@/lib/supabase/client"; import { uploadFile } from "@/components/upload";
    export default function Attendance(){const [message,setMessage]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const selfie=f.get("selfie") as File;let path:string|undefined;if(selfie?.size) path=await uploadFile(selfie,"attendance");navigator.geolocation.getCurrentPosition(async pos=>{const db=createClient(); const {
    data: { user },
    } = await db.auth.getUser();

    if (!user) {
    setMessage("You are not logged in.");
    return;
    } const isOut=f.get("mode")==="out";const row=isOut?{check_out_at:new Date().toISOString(),ending_km:Number(f.get("km")),check_out_selfie_path:path}:{check_in_at:new Date().toISOString(),starting_km:Number(f.get("km")),check_in_selfie_path:path,latitude:pos.coords.latitude,longitude:pos.coords.longitude,current_address:String(f.get("address")),vehicle:String(f.get("vehicle"))};const {error}=await db.from("attendance").upsert({sales_rep_id: user.id , work_date:new Date().toISOString().slice(0,10),...row},{onConflict:"sales_rep_id,work_date"});setMessage(error?.message||"Attendance saved.");},()=>setMessage("Location permission is required."))}return <><h2 className="mb-5 text-2xl font-bold">Attendance</h2><form onSubmit={submit} className="max-w-xl space-y-4 rounded-xl border bg-white p-5"><select name="mode"><option value="in">Attendance in</option><option value="out">Attendance out</option></select><input name="selfie" type="file" accept="image/*" capture="user" required/><input name="km" type="number" min="0" step="0.1" placeholder="Odometer KM" required/><input name="address" placeholder="Current address (for check-in)"/><input name="vehicle" placeholder="Vehicle (for check-in)"/><button className="bg-indigo-600 text-white">Save attendance</button>{message&&<p className="text-sm">{message}</p>}</form></>}
