create type public.user_role as enum ('admin','sales_rep','finance');
create type public.record_status as enum ('active','disabled');
create type public.expense_type as enum ('food','hotel','bus','train','bike_fuel','car_fuel','other');

create table public.profiles (
 id uuid primary key references auth.users(id) on delete cascade, employee_id text unique, full_name text not null, email text unique not null,
 phone text, home_city text, vehicle_type text, role public.user_role not null default 'sales_rep', status public.record_status not null default 'active', created_at timestamptz not null default now()
);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$
begin insert into public.profiles (id,email,full_name) values (new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1))); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create table public.expense_limits (id uuid primary key default gen_random_uuid(), sales_rep_id uuid unique not null references public.profiles(id) on delete cascade, food numeric(12,2) not null default 0, hotel numeric(12,2) not null default 0, bus numeric(12,2) not null default 0, train numeric(12,2) not null default 0, bike_fuel numeric(12,2) not null default 0, car_fuel numeric(12,2) not null default 0, other numeric(12,2) not null default 0, updated_at timestamptz not null default now());
create table public.attendance (id uuid primary key default gen_random_uuid(), sales_rep_id uuid not null references public.profiles(id), work_date date not null default current_date, check_in_at timestamptz, check_out_at timestamptz, check_in_selfie_path text, check_out_selfie_path text, latitude numeric, longitude numeric, current_address text, vehicle text, starting_km numeric, ending_km numeric, travelled_km numeric generated always as (greatest(coalesce(ending_km, starting_km) - coalesce(starting_km, ending_km),0)) stored, unique(sales_rep_id, work_date));
create table public.customers (id uuid primary key default gen_random_uuid(), company_name text not null, owner_name text, contact_number text, address text, category text, sales_rep_id uuid references public.profiles(id), created_by uuid not null references public.profiles(id), created_at timestamptz not null default now());
create table public.customer_visits (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, sales_rep_id uuid not null references public.profiles(id), remark text, photo_path text, follow_up_date date, visited_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), name text not null, sku text unique, unit_price numeric(12,2) not null check(unit_price >= 0), active boolean not null default true);
create table public.orders (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id), sales_rep_id uuid not null references public.profiles(id), payment_type text not null, transport_name text, notes text, total numeric(12,2) not null default 0, created_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid not null references public.products(id), quantity numeric(12,2) not null check(quantity > 0), unit_price numeric(12,2) not null check(unit_price >= 0), line_total numeric(12,2) generated always as (quantity * unit_price) stored);
create table public.expenses (id uuid primary key default gen_random_uuid(), sales_rep_id uuid not null references public.profiles(id), expense_date date not null default current_date, type public.expense_type not null, amount_claimed numeric(12,2) not null check(amount_claimed >= 0), approved_amount numeric(12,2) not null default 0, receipt_path text, remark text, working_location text, status text not null default 'approved' check(status in ('approved','paid')), paid_at timestamptz, transaction_reference text, created_at timestamptz not null default now());

create or replace function public.calculate_expense_approval() returns trigger language plpgsql security definer set search_path = public as $$
declare lim numeric; city text;
begin select home_city into city from profiles where id = new.sales_rep_id;
if city is not null and new.working_location ilike '%' || city || '%' then new.approved_amount := 0; return new; end if;
select case new.type when 'food' then food when 'hotel' then hotel when 'bus' then bus when 'train' then train when 'bike_fuel' then bike_fuel when 'car_fuel' then car_fuel else other end into lim from expense_limits where sales_rep_id = new.sales_rep_id;
new.approved_amount := least(new.amount_claimed, coalesce(lim, 0)); return new; end $$;
create trigger expense_approval before insert or update of amount_claimed,type,working_location,sales_rep_id on public.expenses for each row execute function public.calculate_expense_approval();
create or replace function public.recalculate_order_total() returns trigger language plpgsql security definer set search_path = public as $$ begin update orders set total=(select coalesce(sum(line_total),0) from order_items where order_id=coalesce(new.order_id,old.order_id)) where id=coalesce(new.order_id,old.order_id); return coalesce(new,old); end $$;
create trigger order_total after insert or update or delete on public.order_items for each row execute function public.recalculate_order_total();

alter table public.profiles enable row level security; alter table public.expense_limits enable row level security; alter table public.attendance enable row level security; alter table public.customers enable row level security; alter table public.customer_visits enable row level security; alter table public.products enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.expenses enable row level security;
create or replace function public.is_role(target public.user_role) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role=target and status='active')$$;
create policy "profiles read" on profiles for select using (auth.uid()=id or public.is_role('admin'));
create policy "profiles admin" on profiles for all using (public.is_role('admin')) with check (public.is_role('admin'));
create policy "limits" on expense_limits for all using (public.is_role('admin') or sales_rep_id=auth.uid()) with check (public.is_role('admin'));
create policy "attendance" on attendance for all using (public.is_role('admin') or sales_rep_id=auth.uid()) with check (public.is_role('admin') or sales_rep_id=auth.uid());
create policy "customers select" on customers for select using (public.is_role('admin') or public.is_role('finance') or sales_rep_id=auth.uid()); create policy "customers write" on customers for all using (public.is_role('admin') or sales_rep_id=auth.uid()) with check (public.is_role('admin') or sales_rep_id=auth.uid());
create policy "visits" on customer_visits for all using (public.is_role('admin') or sales_rep_id=auth.uid()) with check (public.is_role('admin') or sales_rep_id=auth.uid());
create policy "products read" on products for select using (true); create policy "products admin" on products for all using (public.is_role('admin')) with check (public.is_role('admin'));
create policy "orders" on orders for all using (public.is_role('admin') or public.is_role('finance') or sales_rep_id=auth.uid()) with check (public.is_role('admin') or sales_rep_id=auth.uid()); create policy "order items" on order_items for all using (exists(select 1 from orders where orders.id=order_id and (orders.sales_rep_id=auth.uid() or public.is_role('admin') or public.is_role('finance')))) with check (exists(select 1 from orders where orders.id=order_id and (orders.sales_rep_id=auth.uid() or public.is_role('admin'))));
create policy "expenses read" on expenses for select using (public.is_role('admin') or public.is_role('finance') or sales_rep_id=auth.uid()); create policy "expenses create" on expenses for insert with check (sales_rep_id=auth.uid()); create policy "expenses finance" on expenses for update using (public.is_role('finance') or public.is_role('admin'));
insert into storage.buckets (id,name,public) values ('sales-files','sales-files',false) on conflict do nothing;
create policy "sales files" on storage.objects for all using (bucket_id='sales-files' and (owner_id=auth.uid() or public.is_role('admin') or public.is_role('finance'))) with check(bucket_id='sales-files' and owner_id=auth.uid());
z